### ISSUE TITLE
Path containing back slashes and forward slashes is not cleaned

### ISSUE THREAD

**Issue by dsherret** [danreeves/path-clean#4]
This pathbuf is not cleaned on windows:

```rust
PathBuf::from("/dir\\../otherDir/test.json").clean()
```

Remains as:

```
/dir\../otherDir/test.json
```

Workaround:

```rust
PathBuf::from(file_path.to_string_lossy().replace("\\", "/")).clean()
```

**Comment by danreeves** [comment]
Sorry, I missed this issue. Could you take a look at PR #7 and let me know if it handles all you think it should. It removes the explicit checks for "/" and uses the Rust std provided tools. This means on Windows it will work with backslashes, but it'll continue to work as it does now on linux/macos because the backslash isn't a valid separator there.
